### ISSUE TITLE
Try/catch grp imports to support Windows usage

### ISSUE THREAD

**Issue by porkcharsui** [tsileo/camlipy#1]
Error during import since `grp` is not available in Windows.

**Comment by tsileo** [comment]
Thanks for the report.

Also can you tell me if you can build the C extension on Windows, or if I should package it in another module ?

Thanks!

**Comment by porkcharsui** [comment]
Building the C extension via setup.py worked after setting `VS90COMNTOOLS` variable based on info found here:
http://www.reddit.com/r/Python/comments/1ariie/using_distutils_and_visual_studio_2012_to_build/

**Config**
- Python 2.7
- VS2012 
- Windows 8 x64

I also saw a warning with this setup.py line (commented it out):
`test_requires=['sh'],`
